version: 2.1
jobs:
  build_test:

    machine:
      image: ubuntu-1604:202004-01

    steps:
      - checkout

      # install, build and test (layers don't keep state)
      - run:
          name: Build & Test
          command: |
            # create and activate venv
            python3.8 -m venv venv
            source venv/bin/activate

            # run automation script.sh
            chmod +x script.sh
            ./script.sh
workflows:
  build_test_docker_build_test: # name of your workflow
    jobs:
      - build_test
