version: 2.1
jobs:
  build_test:

    machine:
      image: ubuntu-1604:202004-01

    steps:
      - checkout

      # install, build and test (layers don't keep state)
      - run: |
          # create and activate venv
          python3.8 -m venv venv
          source venv/bin/activate

          # install cookiecutter
          pip install cookiecutter
          cookiecutter --no-input https://github.com/rednafi/fastapi-nano.git

          # install dependencies
          pip install -r fastapi-nano/requirements.txt
          pip install -r fastapi-nano/requirements-dev.txt

          # run the tests
          pytest fastapi-nano

          # build the docker image
          cd fastapi-nano && docker-compose up -d


workflows:
  build_test_docker_build_test: # name of your workflow
    jobs:
      - build_test
