version: 2.1
jobs:
  build_test:

    machine:
      image: ubuntu-1604:202004-01

    steps:
      - checkout

      # activate venv
      - run: |
          python3.8 -m venv venv
          source venv/bin/activate

      # install, build and test
      - run: make -f "Makefile.dev" install build test

      # build and test the docker image
      - run: make -f "Makefile.dev" docker_build docker_test

workflows:
  build_test_docker_build_test: # name of your workflow
    jobs:
      - build_test
