version: 2.1
jobs:
  build_test:

    machine:
      image: ubuntu-1604:202004-01

    steps:
      - checkout

      # install and build
      - run: |
          python3.8 -m venv venv
          source venv/bin/activate
          pip install cookiecutter
          cookiecutter --no-input https://github.com/rednafi/fastapi-nano.git
          pip install -r fastapi-nano/requirements.txt
          pip install -r fastapi-nano/requirements-dev.txt

      # test
      - run: |
          pytest fastapi-nano

      # build docker image
      - run: |
          cd fastapi-nano && docker-compose up -d

      # test docker image
      - run: |
          curl -X GET "http://localhost:5000/api_b/22" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1YnVudHUiLCJleHAiOjY4NTA4OTczNTJ9.2L7NQKiINLo7_O7z8eAZekK40wHBZpNo3q5C0gm47Wo"


workflows:
  build_test_docker_build_test: # name of your workflow
    jobs:
      - build_test
