version: "3.8"
services:
  {{cookiecutter.repo}}:
    container_name: "{{cookiecutter.repo}}"
    image: "{{cookiecutter.repo}}:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - fastapi-nano
    volumes:
        - .:/code
    ports:
      - 5000:5000
